### ISSUE TITLE
Layer Preview(OpenLayers) with wrong url

### ISSUE THREAD

**Issue by shan1iu** [GeoNode/geoserver-docker#77]
i was trying to preview the new added layer with OpenLayers format but the redirect url starts with genode instead of localhost:8080 hence the openlayer js&css is not loaded correctly

http://geonode/geoserver/....
expected: http://localhost:8080/geoserver/....

i am using docker-compose and here's my yml file

```yml
version: "3.8"
services:
  geoserver:
    image: "geonode/geoserver"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./geoserver/data/:/geoserver_data/data"
````
